- name: plone docker-compose | add plone directory
  file:
    path: "/opt"
    owner: plone
    group: plone
    mode: 0755
    state: directory
  become: yes
  tags:
    - plone

- name: plone docker-compose | add plone {{ project_id }} directory
  file:
    path: "/opt/{{ project_id }}"
    owner: plone
    group: plone
    mode: 0755
    state: directory
  become: yes
  tags:
    - plone

- name: plone | add {{ project_id }} restart script
  template:
    src: restart.j2
    dest: "/opt/{{ project_id }}/restart"
    owner: plone
    group: plone
    mode: 0755
  become: yes
  tags:
    - plone

- name: plone docker-compose | add plone reload script
  template:
    src: reload.j2
    dest: "/opt/{{ project_id }}/reload"
    owner: plone
    group: plone
    mode: 0755
  become: yes
  tags:
    - plone


- name: plone docker-compose | add plone config directory
  file:
    path: "{{ item }}"
    owner: plone
    group: plone
    mode: 0755
    state: directory
  with_items:
    - "/data/{{ project_id }}"
    - "/data/{{ project_id }}/log"
    - "/data/{{ project_id }}/blobstorage"
    - "/data/{{ project_id }}/filestorage"
    - "/backups/{{ project_id }}"
  become: yes
  tags:
    - plone

- name: plone docker-compose |  make sure required docker package is installed
  pip:
    name: '{{ item }}'
    state: present
  with_items:
    - docker=={{ py_docker_version }}
    - docker-compose=={{ docker_compose_version }}
  become: yes
  tags:
    - plone

- name: plone docker-compose |  set docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "/opt/{{ project_id }}/docker-compose.yml"
    owner: plone
    group: plone
    mode: 0700
  notify: restart {{ project_id }}
  become: yes
  tags: plone

- name: plone | add systemd service file to server
  template:
    src: docker-compose.service
    dest: /etc/systemd/system/{{ project_id }}.service
    owner: root
    group: root
  become: yes
  notify:
    - start {{ project_id }}
  tags:
    - plone

- name: plone | start {{ project_id }}
  systemd:
    name: "{{ project_id }}"
    state: started
    enabled: yes
  become_user: root
  become: yes
  tags:
    - plone

# add cron to backup 
- name: docker-compose start backup at 2am.
  cron:
    name: "backup {{ project_id }}"
    minute: "0"
    hour: "2"
    job: "docker-compose -f /plone/{{ project_id }}/docker-compose.yml run --rm -u plone --entrypoint '' -v /backups/{{ project_id }}:/backups zeo bin/backup --no-prompt"
    user: plone
  become: yes
  tags: 
    - plone
    - cron

- name: docker-compose start pack on monday at 3am.
  cron:
    name: "pack {{ project_id }}"
    weekday: "1"
    minute: "0"
    hour: "3"
    job: "docker-compose -f /plone/{{ project_id }}/docker-compose.yml exec zeo bin/zeopack"
    user: plone
  become: yes
  tags: 
    - plone
    - cron

