- name: plone docker-compose | add plone directory
  file:
    path: "/plone"
    owner: plone
    group: plone
    mode: 0755
    state: directory
  become: yes
  tags:
    - plone

- name: plone docker-compose | add plone {{ project_id }} directory
  file:
    path: "/plone/{{ project_id }}"
    owner: plone
    group: plone
    mode: 0755
    state: directory
  become: yes
  tags:
    - plone

- name: plone | add {{ project_id }} restart script
  template:
    src: restart.j2
    dest: "/plone/{{ project_id }}/restart"
    owner: plone
    group: plone
    mode: 0755
  become: yes
  tags:
    - plone

- name: plone docker-compose | add plone reload script
  template:
    src: reload.j2
    dest: "/plone/{{ project_id }}/reload"
    owner: plone
    group: plone
    mode: 0755
  become: yes
  tags:
    - plone


- name: plone docker-compose | add plone config directory
  file:
    path: "{{ item }}"
    owner: plone
    group: plone
    mode: 0755
    state: directory
  with_items:
    - "/data/{{ project_id }}"
    - "/data/{{ project_id }}/log"
    - "/data/{{ project_id }}/blobstorage"
    - "/data/{{ project_id }}/filestorage"
    - "/backups/{{ project_id }}"
  become: yes
  when: image_name != 'plone.restapi'
  tags:
    - plone

- name: plone docker-compose | add plone config directory
  file:
    path: "{{ item }}"
    owner: 500
    group: 500
    mode: 0755
    state: directory
  with_items:
    - "/data/{{ project_id }}"
    - "/data/{{ project_id }}/log"
    - "/data/{{ project_id }}/blobstorage"
    - "/data/{{ project_id }}/filestorage"
    - "/data/{{ project_id }}/instance"
    - "/data/{{ project_id }}/zeoserver"
    - "/backups/{{ project_id }}"
  become: yes
  when: image_name == 'plone.restapi'
  tags:
    - plone

- name: plone docker-compose |  make sure required docker package is installed
  pip:
    name: '{{ item }}'
    state: present
  with_items:
    - docker=={{ py_docker_version }}
    - docker-compose=={{ docker_compose_version }}
  become: yes
  tags:
    - plone

- name: plone docker-compose |  set docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "/plone/{{ project_id }}/docker-compose.yml"
    owner: plone
    group: plone
    mode: 0700
  # notify: reload {{ project_id }}
  become: yes
  tags: plone

- name: docker-compose plone {{ project_id }} service
  docker_service:
    project_name: '{{ project_id }}'
    pull: yes
    project_src: "/plone/{{ project_id }}"
  # notify: reload {{ project_id }}
  become: true
  become_user: plone
  tags:
    - plone
    - update
  # assert:
  #   that:
  #     - "web.plone_web_1.state.running"
  #     - "db.plone_db_1.state.running"




# add cron to backup 
- name: docker-compose start backup at 2am.
  cron:
    name: "backup {{ project_id }}"
    minute: "0"
    hour: "2"
    job: "docker-compose -f /plone/{{ project_id }}/docker-compose.yml run --rm -u plone --entrypoint '' -v /backups/{{ project_id }}:/backups zeo bin/backup --no-prompt"
    user: plone
  become: yes
  tags: 
    - plone
    - cron

- name: docker-compose start pack on monday at 3am.
  cron:
    name: "pack {{ project_id }}"
    weekday: "1"
    minute: "0"
    hour: "3"
    job: "docker-compose -f /plone/{{ project_id }}/docker-compose.yml exec zeo bin/zeopack"
    user: plone
  become: yes
  tags: 
    - plone
    - cron

