---
- name: start {{ project_id }}
  systemd:
    name: "{{ project_id }}"
    state: started
    enabled: yes

- name: restart {{ project_id }}
  systemd:
    name: "{{ project_id }}"
    state: restarted
    enabled: yes
