- name: traefik docker-compose | add traefik directory
  file:
    path: "/home/plone/traefik"
    owner: plone
    group: plone
    mode: 0755
    state: directory
  become: yes
  tags:
    - traefik

- name: Ensures acme.json file exists
  file:
    path: "/home/plone/traefik/acme.json"
    owner: plone
    group: plone
    state: touch
    mode: 0600
  become: yes
  tags:
    - traefik

- name: Adding traefik.toml file
  template:
    src: ../templates/traefik.toml.j2
    dest: "/home/plone/traefik/traefik.toml"
    owner: plone
    group: plone
    mode: 0600
  become: yes
  tags:
    - traefik

- name: Create proxy network
  docker_network:
    name: proxy
  tags:
    - traefik

- name: plone docker-compose |  set docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "/home/plone/traefik/docker-compose.yml"
    owner: plone
    group: plone
    mode: 0700
  become: yes
  tags: traefik

- name: docker-compose plone {{ project_id }} service
  docker_service:
    project_name: traefik
    pull: yes
    project_src: "/home/plone/traefik"
  become: true
  become_user: plone
  tags:
    - traefik

