- name: traefik docker-compose | add traefik directory
  file:
    path: "/opt/traefik"
    owner: plone
    group: plone
    mode: 0755
    state: directory
  become: yes
  tags:
    - traefik

- name: Ensures acme.json file exists
  file:
    path: "/opt/traefik/acme.json"
    owner: plone
    group: plone
    state: touch
    mode: 0600
  become: yes
  tags:
    - traefik

- name: Adding traefik.toml file
  template:
    src: ../templates/traefik.toml.j2
    dest: "/opt/traefik/traefik.toml"
    owner: plone
    group: plone
    mode: 0600
  become: yes
  tags:
    - traefik

- name: Create proxy network
  docker_network:
    name: proxy
  tags:
    - traefik

- name: plone docker-compose |  set docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "/opt/traefik/docker-compose.yml"
    owner: plone
    group: plone
    mode: 0700
  notify: restart traefik
  become: yes
  tags: traefik

- name: traefik | add systemd service file to server
  template:
    src: traefik.service
    dest: /etc/systemd/system
    owner: root
    group: root
  become: yes
  notify:
    - start traefik
  tags:
    - traefik

- name: traefik | start traefik
  systemd:
    name: traefik
    state: started
    enabled: yes
  become_user: root
  become: yes
  tags:
    - traefik


